### ISSUE TITLE
Elevation profile too coarse compared to Google Earth Pro

### ISSUE THREAD

**Issue by 0xCoto** [Jorl17/open-elevation#43]
I'm trying to follow [this example](https://www.geodose.com/2018/03/create-elevation-profile-generator-python.html) (with except with `s=1000` to get high-accuracy data), and get the following elevation profile:

![Screen Shot 2021-04-12 at 12 06 50 AM](https://user-images.githubusercontent.com/25392776/114321319-fc5bcc80-9b22-11eb-8afa-d65af383e7c5.png)

However, using Google Earth Pro, I get a much finer elevation profile (the accuracy of the start and end points appear OK):

![image](https://user-images.githubusercontent.com/25392776/114321349-1d242200-9b23-11eb-8e71-d5bac27c3d70.png)

Do we know why that is? Does Google use a different dataset, or does it essentially apply some interpolation to the results I get with the `open-elevation` API? The location is Greece in case that matters.

I'm also unable to set `s=2000` or higher for some reason, so I can't increase the resolution more apparently:

```
Traceback (most recent call last):
  File "/Users/username/Desktop/Radio Astronomy/linkCoverage/example_elevation.py", line 64, in <module>
    fp=urllib.request.urlopen(response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**Comment by 0xCoto** [comment]
@Jorl17 @ligi @chrislukic Any ideas?

**Comment by chrislukic** [comment]
Google's elevation map is comprised of the data from thousands of elevation surveys done by local and national governments around the world. They have a team of data scientists working to correct these surveys and assemble them into a very fine grain global elevation map. That map is then further corrected for errors.

This open source project uses just one set of elevation data data that was recorded by the space shuttle in 2000. Although, the readme mentions it as a Google API alternative, this is true only in the sense that both provide a GPS to elevation mapping.
